{% set name = "xoak" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aa6e30ac9733a4e10b20d9a90cbfe987fcdd3e14b0b6e514392238cd54fad703

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - dask
    - numpy
    - scipy
    - xarray

test:
  imports:
    - xoak

about:
  home: https://github.com/ESM-VFC/xoak
  license: MIT
  license_file: LICENSE
  summary: Xarray extension for selecting irregular, n-dimensional data.

extra:
  recipe-maintainers:
    - benbovy
    - willirath
