{% set name = "xoak" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dcad57c35818926032beef2dc78ef7bd99349bfd427cd3a87699b91c976946d9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - dask
    - numpy
    - scipy
    - xarray

test:
  imports:
    - xoak

about:
  home: https://github.com/ESM-VFC/xoak
  license: MIT
  license_file: LICENSE
  summary: Xarray extension for selecting irregular, n-dimensional data.

extra:
  recipe-maintainers:
    - benbovy
    - willirath
