{% set name = "xoak" %}
{% set version = "0.2.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 04700c697444ab734581aa0fd5b30d4ca70018ee491472643c5286788cf9e797

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - dask
    - numpy
    - scipy
    - xarray

test:
  imports:
    - xoak
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/xarray-contrib/xoak
  license: MIT
  license_file: LICENSE
  summary: Xarray extension for selecting irregular, n-dimensional data.

extra:
  recipe-maintainers:
    - benbovy
    - willirath
